"""Can a cheap supervised filter cut false positives without losing true positives?

`tail_sensitivity.py` establishes that with the two unsupervised rankers already in the
repo, reaching *every* captured mitosis costs 24-97% of the candidate pool -- i.e. the
"flag every nucleus" outcome the product is trying to avoid. This asks whether a small
supervised classifier over **cheap morphometric features** (no embeddings, no CNN, no GPU)
moves the tail, which is the "add a filter step that drops FPs without losing TPs" idea
measured rather than assumed.

Protocol
--------
* Candidates are the same seedless `nucleus_blobs` set, so the proposal ceiling is
  identical across every arm and only the *ordering* is under test.
* Features are the region properties `nucleus_blobs` already computes internally plus
  window statistics on unclipped hematoxylin OD -- 22 numbers, all O(1) per candidate.
* **Leave-one-ROI-out.** Training on candidates from the ROI being scored would leak: the
  positives are a few hundred specific objects and a flexible model memorises them. Each
  ROI is scored by a model that never saw it. ROIs come from four different tumour
  domains, so this also probes cross-domain transfer, which is the deployment condition.
* The metric is the same tail statistic: candidates read to reach each sensitivity level.

Writes results/fp_filter_features.csv (cached) and results/fp_filter_tail.csv.
"""

from __future__ import annotations

import os
import pathlib
import time

import numpy as np
import pandas as pd
from skimage.measure import label, regionprops_table

from midog_utils import baselines as bl
from midog_utils import chromatin as cm
from midog_utils import dataset as ds
from midog_utils import evaluate as ev

ROIS = ["301.tiff", "300.tiff", "246.tiff", "245.tiff", "201.tiff", "202.tiff", "405.tiff"]
# 63 MB of raw per-candidate features -- a pure cache, regenerated by deleting it.
# Kept out of results/ so it cannot be swept into a commit; every load-bearing
# summary this script produces still lands in results/.
FEATCACHE = os.environ.get("FP_FEATCACHE", ".cache_tail/fp_filter_features.csv")
QUANTS = [0.50, 0.90, 0.95, 0.98, 0.99, 1.00]

SHAPE_PROPS = ("area", "perimeter", "eccentricity", "solidity", "extent",
               "major_axis_length", "minor_axis_length", "equivalent_diameter",
               "euler_number", "feret_diameter_max",
               "intensity_mean", "intensity_max", "intensity_min")


def candidates_with_features(rgb: np.ndarray) -> pd.DataFrame:
    """`nucleus_blobs`' components, kept under the same area gate, with richer props."""
    mask = bl.tissue_mask(rgb)
    h_chan = bl.to_hematoxylin(rgb)
    thr = bl._tiled_otsu_threshold(h_chan, mask, 512)
    binary = (h_chan > thr) & mask
    lab = label(binary, connectivity=2)

    tab = regionprops_table(lab, intensity_image=h_chan,
                            properties=("centroid",) + SHAPE_PROPS)
    df = pd.DataFrame(tab).rename(columns={"centroid-0": "cy", "centroid-1": "cx"})
    df = df[(df["area"] >= 80) & (df["area"] <= 4000)].reset_index(drop=True)

    # derived shape ratios -- scale-free, so they transfer across scanners better than area
    df["aspect"] = df["minor_axis_length"] / df["major_axis_length"].clip(lower=1e-6)
    df["circularity"] = 4 * np.pi * df["area"] / df["perimeter"].clip(lower=1e-6) ** 2
    df["intensity_range"] = df["intensity_max"] - df["intensity_min"]
    # `nucleus_blobs`' own ranking key, so the supervised arm strictly contains it
    df["score"] = df["intensity_mean"]
    return df


def add_window_features(df: pd.DataFrame, hem_od: np.ndarray) -> pd.DataFrame:
    """Chromatin density at three window sizes plus a local-context contrast.

    A single 51 px window conflates the object with its surround. Reading 31/51/81 px and
    differencing against a 121 px context makes "this object is darker than its
    neighbourhood" expressible, which a per-ROI absolute OD value is not -- optical
    density is uncalibrated between scanners, so only *within-image* contrasts transfer.
    """
    for w in (31, 51, 81):
        df[f"od{w}"] = [cm.chromatin_density(hem_od, cx, cy, window=w)
                        for cx, cy in zip(df["cx"], df["cy"])]
    df["od_ctx"] = [cm.chromatin_density(hem_od, cx, cy, window=121, frac=0.50)
                    for cx, cy in zip(df["cx"], df["cy"])]
    df["od_contrast"] = df["od51"] - df["od_ctx"]
    df["od_falloff"] = df["od31"] - df["od81"]
    return df


def build_features() -> pd.DataFrame:
    if os.path.exists(FEATCACHE):
        print(f"reusing {FEATCACHE}", flush=True)
        return pd.read_csv(FEATCACHE)
    _images, ann = ds.load_annotations()
    meta = ds.load_slide_metadata()
    frames = []
    for fn in ROIS:
        t0 = time.time()
        path = f"images/{fn}"
        rgb = ds.load_roi(path)
        radius = ev.radius_px(ds.roi_mpp(path))
        gt = ds.image_annotations(ann, fn).reset_index(drop=True)
        hem_od = cm.hematoxylin_od(rgb)

        df = candidates_with_features(rgb)
        df = add_window_features(df, hem_od)
        det, _ = ev.bucket_detections(df.sort_values("score", ascending=False)
                                        .reset_index(drop=True), gt, radius)
        det["y"] = (det["bucket"] == ev.HUMAN_CORRECT_LABEL).astype(int)
        det["file_name"] = fn
        det["domain"] = meta.loc[meta.image_id == int(fn.split(".")[0]), "Tumor"].iloc[0]
        det["n_gt_mitotic"] = int((gt.category_id == ds.MITOTIC).sum())
        frames.append(det)
        print(f"{fn}: {len(det)} cand, {det.y.sum()} pos, {time.time()-t0:.0f}s", flush=True)
    out = pd.concat(frames, ignore_index=True)
    d = os.path.dirname(FEATCACHE)
    if d:
        os.makedirs(d, exist_ok=True)
        # the cache dir ignores its own contents, so a fresh clone never carries it
        pathlib.Path(d, '.gitignore').write_text('*\n')
    out.to_csv(FEATCACHE, index=False)
    return out


FEATURES = list(SHAPE_PROPS) + ["aspect", "circularity", "intensity_range",
                                "od31", "od51", "od81", "od_ctx", "od_contrast", "od_falloff"]


def tail_from_scores(sub: pd.DataFrame, score: np.ndarray) -> list[dict]:
    """Depth to reach each sensitivity level when the ROI is ordered by ``score``.

    Sensitivity is over the mitoses the *proposal stage captured*, not over all annotated
    mitoses -- the ones it missed are unreachable at any depth and are reported separately
    as the ceiling. Depth counts candidates read, so the top-ranked candidate costs one.
    """
    order = np.argsort(-score, kind="mergesort")
    y = sub["y"].to_numpy()[order]
    hits = np.flatnonzero(y == 1)
    n_found = len(hits)
    rows = []
    for q in QUANTS:
        if not n_found:
            continue
        i = int(np.ceil(q * n_found)) - 1
        depth = int(hits[i]) + 1
        rows.append(dict(quantile=q, depth=depth, n_found=n_found,
                         frac_of_pool=round(depth / len(y), 4),
                         fp_per_tp=round((depth - (i + 1)) / (i + 1), 1)))
    return rows


def main():
    from sklearn.ensemble import HistGradientBoostingClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.pipeline import make_pipeline
    from sklearn.preprocessing import StandardScaler

    df = build_features()
    X_all = df[FEATURES].to_numpy(dtype=np.float64)
    X_all = np.nan_to_num(X_all, nan=0.0, posinf=0.0, neginf=0.0)

    rows = []
    for fn in ROIS:
        te = (df["file_name"] == fn).to_numpy()
        tr = ~te
        sub = df[te].reset_index(drop=True)
        ytr = df["y"].to_numpy()[tr]

        arms = {
            "blob_score": sub["score"].to_numpy(),
            "chromatin_od51": np.nan_to_num(sub["od51"].to_numpy(), nan=-1e9),
        }
        # class_weight/balanced: ~1 positive per 150 candidates, so an unweighted fit
        # puts the whole decision boundary in the negatives.
        lr = make_pipeline(StandardScaler(),
                           LogisticRegression(max_iter=2000, class_weight="balanced"))
        lr.fit(X_all[tr], ytr)
        arms["logreg_loro"] = lr.predict_proba(X_all[te])[:, 1]

        gb = HistGradientBoostingClassifier(
            max_iter=300, learning_rate=0.08, max_leaf_nodes=15,
            l2_regularization=1.0, class_weight="balanced", random_state=0)
        gb.fit(X_all[tr], ytr)
        arms["hgb_loro"] = gb.predict_proba(X_all[te])[:, 1]

        for name, s in arms.items():
            for r in tail_from_scores(sub, np.asarray(s, dtype=np.float64)):
                rows.append(dict(file_name=fn, ranker=name, n_pool=len(sub),
                                 n_gt_mitotic=int(sub["n_gt_mitotic"].iloc[0]), **r))
        print(f"{fn} done", flush=True)

    out = pd.DataFrame(rows)
    out.to_csv("results/fp_filter_tail.csv", index=False)
    pd.set_option("display.width", 250)
    piv = out.pivot_table(index=["file_name", "ranker"], columns="quantile",
                          values="depth", aggfunc="first")
    base = out.groupby(["file_name", "ranker"])[["n_pool", "n_found"]].first()
    print("\n=== candidates read to reach each sensitivity level (of captured) ===")
    print(base.join(piv).to_string())


if __name__ == "__main__":
    main()
